# Generated by Django 4.2.15 on 2024-08-22 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='제목')),
                ('description', models.TextField(verbose_name='해야할 일')),
                ('start_date', models.DateField(verbose_name='해아할 일 시작 날짜')),
                ('end_date', models.DateField(verbose_name='해야할 일 마감 날짜')),
                ('is_completed', models.BooleanField(default=False, verbose_name='완료 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='수정 시간')),
            ],
        ),
    ]
